#version: '3.9'

services:
  mongodb:
    image: mongo:7.0
    container_name: crud_mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: users_crud

  backend:
    build: ./backend
    container_name: crud_backend
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
      NODE_ENV: production
      MONGODB_URI: mongodb://mongodb:27017/users_crud
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: crud_frontend
    restart: unless-stopped
    ports:
      - '5173:80'
    depends_on:
      - backend

volumes:
  mongo_data:
